# Blog
keywords: JavaScript, HTML, CSS, Vue.js, Koa.js
author: Zhu Chu, mystery490815101@gmail.com
description: Everything is for DOPAMINE.
avatar: /images/favicon.png

# Social Accounts
twitter:
rss:
weibo: i490815101
instagram:
github: MegrezZhu
facebook:

# Comment
duoshuo:
disqus:
gentie:
